services:
  - type: web
    name: timeseries
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn myproject.wsgi --bind 0.0.0.0:$PORT"
    plan: free
    regions:
      - oregon
